name: assets_indexer
description: To generate indexed constants for your assets in dart/flutter project! Inspired by android R.java concept
version: 0.0.8
homepage: https://github.com/yanncabral/assets_indexer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: 
  mustache: 
  numbers_to_words:  
  quartet: ^0.1.1
 
dev_dependencies:
  build_config: 
  build_runner: 